spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eureka-user
  application:
    name: eureka-client-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true