server:
  port: 9999
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
zuul:
  routes:
    eureka-client-user:
      path: /api/user/**
      service-id: eureka-client-user